name: deploy-common
on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: git config --global user.email "me@edpasenidis.tech" && git config --global user.name "Edward Pasenidis"
      - run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: npm version patch && npm publish
